/// Flutter icons GuildWars
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GuildWars
///      fonts:
///       - asset: fonts/GuildWars.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GuildWarsIcons {
  GuildWarsIcons._();

  static const _kFontFam = 'GuildWars';

  static const IconData achievement = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData daily = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData equipment = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData hero = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData inventory = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData mastery = const IconData(0xe805, fontFamily: _kFontFam);
}
